package com.halseyzsmith.hzssbactuator.bootstrap;

public class Paragraphs {

    // Author Bios
    public static final String JTH_BIO = "John Twelve Hawks (pseudonym) is the author of the 2005 dystopian novel The Traveler and its sequels, The Dark River and The Golden City, collectively comprising the Fourth Realm Trilogy. The trilogy has been translated into 25 languages and has sold more than 1.5 million books. The trilogy was followed five years later by a fourth book, Spark, and a non-fiction eBook, Against Authority. \"John Twelve Hawks\" is a pseudonym and his real identity is unknown.";
    public static final String RAND_BIO = "Ayn Rand (born Alisa Zinovyevna Rosenbaum; February 2, 1905 – March 6, 1982) was a Russian-American writer and philosopher. She is known for her two best-selling novels, The Fountainhead and Atlas Shrugged, and for developing a philosophical system she named Objectivism. Born and educated in Russia, she moved to the United States in 1926. She had a play produced on Broadway in 1935 and 1936. After two early novels that were initially unsuccessful, she achieved fame with her 1943 novel, The Fountainhead. In 1957, Rand published her best-known work, the novel Atlas Shrugged. Afterward, she turned to non-fiction to promote her philosophy, publishing her own periodicals and releasing several collections of essays until her death in 1982.";

    // JTH Book Summaries
    public static final String TRAVELER_SUMMARY = "In London, Maya, a young woman trained to fight by her powerful father, uses the latest technology to elude detection when walking past the thousands of surveillance cameras that watch the city. In New York, a secret shadow organization uses a victim’s own GPS to hunt him down and kill him. In Los Angeles, Gabriel, a motorcycle messenger with a haunted past, takes pains to live \"off the grid\" — free of credit cards and government IDs. Welcome to the world of The Traveler — a world frighteningly like our own.In this compelling novel, Maya fights to save Gabriel, the only man who can stand against the forces that attempt to monitor and control society. From the back streets of Prague to the skyscrapers of Manhattan, The Traveler portrays an epic struggle between tyranny and freedom. Not since 1984 have readers witnessed a Big Brother so terrifying in its implications and in a story that so closely reflects our lives.";
    public static final String DARK_RIVER_SUMMARY = "A fearless heroine.... A tale of brother against brother.... A battle for hope and freedom. Two brothers born into a race of Travelers—prophets able to journey to different realms of consciousness—have just discovered that their long lost father may still be alive. Gabriel, who could be humanity’s savior, and his guardian, Maya, want to protect him. Michael wants to destroy him and with it humanity’s hope for freedom. As they race across the globe, their frantic search puts them on a collision course, and the fate of the world hangs in the balance.";
    public static final String GOLDEN_CITY_SUMMARY = "In The Golden City, Twelve Hawks delivers the climax to his spellbinding epic. Struggling to protect the legacy of his Traveler father, Gabriel faces troubling new questions and relentless threats. His brother Michael, now firmly allied with the enemy, pursues his ambition to wrest power from Nathan Boone, the calculating leader of the Brethren. And Maya, the Harlequin warrior pledged to protect Gabriel at all costs, is forced to make a choice that will change her life forever. A riveting blend of high-tech thriller and fast-paced adventure, The Golden City will delight Twelve Hawks's many fans and attract a new audience to the entire trilogy.";
    public static final String SPARK_SUMMARY = "Shifting with riveting precision from New York to London, Paris to New Delhi, Spark is a thriller that delves into the surveillance state we prognosticate  today . . . and will live in tomorrow. In the hands of master storyteller John Twelve Hawks, a unique character’s startling transformation comes to life, making Spark a thriller that resonates and satisfies on many levels.";

    // Ayn Rand Summaries
    public static final String ANTHEM_SUMMARY = "Anthem is a dystopian fiction novella by Ayn Rand, written in 1937 and first published in 1938 in England. It takes place at some unspecified future date when mankind has entered another dark age characterized by irrationality, collectivism, and socialistic thinking and economics. Technological advancement is now carefully planned (when it is allowed to occur at all) and the concept of individuality has been eliminated.";
    public static final String ATLAS_SHRUGGED_SUMMARY = "Atlas Shrugged, a modern classic and Rand’s most extensive statement of Objectivism—her groundbreaking philosophy—offers the reader the spectacle of human greatness, depicted with all the poetry and power of one of the twentieth century’s leading artists.";
    public static final String FOUNTAINHEAD_SUMMARY = "This modern classic is the story of intransigent young architect Howard Roark, whose integrity was as unyielding as granite...of Dominique Francon, the exquisitely beautiful woman who loved Roark passionately, but married his worst enemy...and of the fanatic denunciation unleashed by an enraged society against a great creator. As fresh today as it was then, Rand’s provocative novel presents one of the most challenging ideas in all of fiction—that man’s ego is the fountainhead of human progress...";
    public static final String WE_THE_LIVING_SUMMARY = "First published in 1936, We the Living portrays the impact of the Russian Revolution on three human beings who demand the right to live their own lives and pursue their own happiness. It tells of a young woman’s passionate love, held like a fortress against the corrupting evil of a totalitarian state.";

}
